### ISSUE TITLE
Dockerise

### ISSUE THREAD

**Issue by bede** [bede/hostile#18]

**Comment by mbhall88** [comment]
Now that you have a conda package for this you maybe don't even need to do this as biocontainers build a container for every conda package (https://quay.io/repository/biocontainers/hostile?tab=tags).

I guess that doesn't help though if you want a container for every commit. Biocontainers will only give you containers for releases that are also added to bioconda

**Comment by bede** [comment]
Thanks, a good point, I hadn't realised the docker image was available already with all the bad messages I've been getting from Azure pipelines about the state of the recipe! I also can't conda install it at the moment: https://github.com/bede/hostile/issues/9

I think I'll put tags in another registry however – was thinking of using micromamba for the Dockerfile, will investigate

**Comment by bede** [comment]
Ok it looks like these are being auto updated pretty swiftly, fantastic. May add another registry for boring engineering reasons, but not urgent now.
