### ISSUE TITLE
Discard partially downloaded indexes

### ISSUE THREAD

**Issue by bede** [bede/hostile#20]
Currently if a genome/index download is abandoned, Hostile may think it's present and correct leading to errors. Could download to a temp location and move into `$XDG_DATA_DIR` or download and rename etc

**Comment by mbhall88** [comment]
You could possibly do a sha256 check on the existing file? That way you can be certain if it's what you expect or not? I have some code for doing this in tbpore you can use if you want to go that route? 

https://github.com/mbhall88/tbpore/blob/1225472de54a2bd6c034b41f4540a1f539473822/tbpore/utils.py#L72-L87

**Comment by bede** [comment]
I've mitigated this in 0.1.0 by downloading indexes to a temporary file before moving (minimap2) or extracting (Bowtie2) into the destination XDG data directory. That way if the download is interrupted, the aligner won't try to use a corrupted ref.

If I implement checksum validation, I guess the obvious way avoiding hardcoding would be to put checksum files with the same filename prefix as the ref/index in object storage? Any thoughts @mbhall88?

**Comment by mbhall88** [comment]
Yeah I think the "standard" method is putting the checksum in the storage location ([e.g.](https://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/Acidianus_infernus/latest_assembly_versions/GCF_009729545.1_ASM972954v1/)). I think, as you say, this avoids hardcoding the checksums.

**Comment by bede** [comment]
Thanks @mbhall88, I've added checksum verification in https://github.com/bede/hostile/commit/1e81debf73c4279f9682de08c1edf0791b15d47f for release in v1.
