### ISSUE TITLE
Regarding the choice of Reference genomes

### ISSUE THREAD

**Issue by LilyAnderssonLee** [bede/hostile#27]
Hi,
I've noticed that Hostile provides three options for reference genomes. I'm wondering which reference I should select in order to remove human genes from my microbiome samples before conducting metagenomics classification. 

Could you please explain the advantages of including HLA, argos985, and mycob140 in the host removal process, particularly in the context of clinical samples with CNS infections?

**Comment by bede** [comment]
Hi Lili,
Great question, this should be better documented. The default database is called human-t2t-hla and is downloaded automatically when running Hostile for the first time after a clean install. This comprises the T2T-CHM13v2.0 human reference and the IPD-IMGT/HLA human leukocyte antigen database. HLA sequences are included to enable removal of a relatively small number of highly identifiable human reads from the MHC region. This is a sensible default option.

While Hostile is already more conservative than other tools in my testing (it removes fewer non-human reads), two other databases (and soon more) are provided to further reduce false positive removal of non-human reads.

The human-t2t-hla-argos985 reference is the same as human-t2t-hla except that it is masked against the 985 complete FDA-ARGOS bacterial genomes, including many human pathogens.

The human-t2t-hla-argos985-mycob140 reference is the same as human-t2t-hla-argos985 except that it is also masked against 140 mycobacterial genomes.

For your application, any of these databases are good choices, however I would recommend using the human-t2t-hla-argos985 reference, as it's possible it will prevent some bacterial reads being wrongly removed, at the expense of not removing a tiny fraction of human reads. How many more microbial reads are removed with an unmasked database varies a lot between species, although data in the preprint gives some indication of the difference made for a metagenome. Let me know if you have more Qs.

**Comment by bede** [comment]
I've added notes to the readme explaining the benefits of using `human-t2t-hla-argos985` over the standard `human-t2t-hla` index when processing bacterial genomes, so am closing this. Feel free to reopen or otherwise reach out with more questions and I'll do my best to help. Thanks!

**Comment by LilyAnderssonLee** [comment]
@bede   Thanks a lot for your very detailed information. I will test human T2T-HLA-argos985-mycob140 in our case:)
