### ISSUE TITLE
I think you can use --name (-n) on the mamba command line to override the environment name in the env file.

### ISSUE THREAD

**Issue by bdklahn** [bede/hostile#33]
no need for manual string replacing :-)

I, at least, know it works for `env create`.

https://github.com/bede/hostile/blob/57be277e89204ef8e63ceeaa704d13a82da82dec/Dockerfile#L4-L5

**Comment by bede** [comment]
Thanks for this, committed in https://github.com/bede/hostile/commit/c2f38c32bcdc405c92cce11b77b819378f6a65c9
