### ISSUE TITLE
Dockerfile fails: process "/bin/sh -c mamba env update -n base -f hostile/environment.yml" did not complete successfully

### ISSUE THREAD

**Issue by dterumalai** [bede/hostile#43]
Dear maintainer,

Since today, when I am trying to build the docker image using your Dockerfile, I am experiencing issues:

```
Dockerfile:4
--------------------
   2 |     FROM condaforge/miniforge3:latest
   3 |     RUN git clone https://github.com/bede/hostile.git
   4 | >>> RUN mamba env update -n base -f hostile/environment.yml
   5 |     RUN pip install ./hostile[dev]
   6 |     RUN cd hostile && pytest
--------------------
ERROR: failed to solve: process "/bin/sh -c mamba env update -n base -f hostile/environment.yml" did not complete successfully: exit code: 1
```

Any idea on what is going wrong?

Best,
Dillenn

**Comment by bede** [comment]
Thanks for flagging this @dterumalai, I've reproduced. It's a classic case of conda deps becoming unsolvable over time. Hopefully I can fix by bumping versions, but failing that I will make a Dockerfile without reliance on conda.

In case you are in a hurry, the key non-python deps are:
  - samtools>=1.17
  - minimap2>=2.26
  - bowtie2>=2.4.5
  - bedtools (needed only for masking)

Pre built containers:
https://biocontainers.pro/tools/hostile

**Comment by dterumalai** [comment]
Hi @bede, 
Thanks for the quick answer. Happy that you managed to reproduce the issue and identified the problem. I am not in a rush so I will wait for your fix.

Have a nice day!

**Comment by bede** [comment]
Thanks for your patience, I believe that the issue was caused by the latest Miniforge using Python 3.12. I've now pinned a compatible base image – feel free to reopen if you still have problems.
