### ISSUE TITLE
Hostile crashes if path has spaces in it

### ISSUE THREAD

**Issue by pvanheus** [bede/hostile#45]
Some Windows users have spaces in their usernames which propagate e.g. to the epi2melabs directory where hostile data is stored. This causes a crash in hostile.

**Comment by bede** [comment]
Thanks Peter – while FASTQ and index paths are quoted, e.g. BIN_PATH is not, which I imagine could cause this issue. Do you happen to know if the problem arises when accessing indexes, the minimap2/bowtie2 binaries, or something else?

**Comment by bede** [comment]
Is this still an issue @pvanheus? If not please could you give an example where it breaks? I've quoted BIN_PATH in 6ad8aebbdfc94ec173c8ae9a0e0978598dd50b84

**Comment by pvanheus** [comment]
Sorry, meant to close this. I verified that the problem wasn't with hostile itself.

**Comment by bede** [comment]
Thanks, just wanted to check!
