### ISSUE TITLE
Clarify terminology with respect to unpaired/SE reads

### ISSUE THREAD

**Issue by bede** [bede/hostile#47]
References to `unpaired` reads in the CLI help and README are potentially ambiguous, possibly interpreted as reads lacking a mate for QC reasons or otherwise. It is intended to refer to single end (SE) short reads, for instance Illumina reads that have been merged. This should be reviewed and clarified. Highlighted by @jfy133 (https://github.com/bede/hostile/issues/46).

**Comment by jfy133** [comment]
I think that would help future me yes, thank you @bede !
